#!/usr/bin/env bash

set -xeuo pipefail
cargo kernel-x86_64 "$@"
cargo limine-x86_64 "$@"
cargo kernel-aarch64 "$@"
cargo limine-aarch64 "$@"
cargo oro-clippy-common
cargo oro-clippy-x86_64
cargo oro-clippy-aarch64
env RUSTFLAGS="-D warnings" cargo oro-doc-x86_64
env RUSTFLAGS="-D warnings" cargo oro-doc-aarch64
cargo fmt --all -- --check
